### PR TITLE
Mc issue 352 search endpoint

### PR DESCRIPTION
**Pull request by maxachis**
#### Fixes

* https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/352
* Should not be merged until after #46 

#### Description

* Creates Search Endpoint which, when given a state, and optionally a county, locality, and/or record type, returns all data sources corresponding to the given search parameters.

#### Testing

* Run associated tests in `tests` directory. Confirm all function as intended.

#### Performance

* Running the integration test for this endpoint took 163ms.

#### Docs

* https://app.gitbook.com/o/-MXypK5ySzExtEzQU6se/s/-MXyolqTg_voOhFyAcr-/~/changes/508/api/endpoints/data-sources-database#example-1

### CODE REVIEW

**Review by josh-chamberlain — COMMENTED** [review]
I'm trying to test this one, but I'm not able to get a result back. No matter what I try, I seem to get the same response:

```
http://localhost:5000/search?state=MI&county=Wayne&locality=Detroit
```

```
<!doctype html>
<html lang=en>
  <head>
    <title>ValueError: None is not a valid RecordCategories
 // Werkzeug Debugger</title>
..
..
```

I'm testing using Postman. I used the API to create a user, then used the API key in the header to try to hit the endpoint a bit.

**Comment by maxachis** [comment]
> I'm trying to test this one, but I'm not able to get a result back. No matter what I try, I seem to get the same response:
> 
> ```
> http://localhost:5000/search?state=MI&county=Wayne&locality=Detroit
> ```
> 
> ```
> <!doctype html>
> <html lang=en>
>   <head>
>     <title>ValueError: None is not a valid RecordCategories
>  // Werkzeug Debugger</title>
> ..
> ..
> ```
> 
> I'm testing using Postman. I used the API to create a user, then used the API key in the header to try to hit the endpoint a bit.

In this case, the Resource was not properly handling cases where the Record Category was none. Just made a commit to address this!

> * the docs linked use `record_type` in the URL example and `record_category` in the params; when I try defining a record_category, I can't get one to land.
> ```
> http://localhost:5000/search?state=MI&county=Wayne&locality=Detroit&record_category=Info about agencies
> ```

I corrected the URL example (which was based off an old version of the code), so give it a shot now! Note that the url will need to exactly match the values as they are listed (which in this case is "Info about Agencies"). That can be modified if desired! 

The URL may also need to be encoded, so as to be URL friendly (i.e., as `Info%20about%20Agencies`).

The URL I used in my integration test (an example which I could perhaps provide in the Gitbook) is `"/search?state=Pennsylvania&county=Allegheny&locality=Pittsburgh&record_category=Police%20%26%20Public%20Interactions"`

**Comment by josh-chamberlain** [comment]
After pulling your changes, partial success! When I don't use a record_type, I get results.

(fig 1) However, I can't get the example to work. Trying with `Info%20about%20agencies`, I get `ValueError: &#39;Info about agencies&#39; is not a valid RecordCategories`. I'm not adding those apostrophes anywhere.

(fig 2) When I use your example `/search?state=Pennsylvania&county=Allegheny&locality=Pittsburgh&record_category=Police%20%26%20Public%20Interactions`

```
    <title>psycopg2.errors.UndefinedTable: relation &#34;record_types&#34; does not exist
LINE 27:                     record_types ON data_sources.record_type...
                             ^
```

Could I be using the wrong db, maybe?

### fig 1
Screen Shot 2024-07-11 at 11 05 02 AM


### fig 2
Screen Shot 2024-07-11 at 11 03 14 AM

**Comment by maxachis** [comment]
> @maxachis After pulling your changes, partial success! When I don't use a record_type, I get results.
> 
> (fig 1) However, I can't get the example to work. Trying with `Info%20about%20agencies`, I get `ValueError: &#39;Info about agencies&#39; is not a valid RecordCategories`. I'm not adding those apostrophes anywhere.
> 
> (fig 2) When I use your example `/search?state=Pennsylvania&county=Allegheny&locality=Pittsburgh&record_category=Police%20%26%20Public%20Interactions`

@josh-chamberlain 

For the second point, I've sent you a message about that in Discord! 

For the first point, that's partly because it is _very_ precise about the string. It has to be an exact match (and the category, as described, was "Info about Agencies", rather than "Info about agencies":

image

I'm debating whether I should have them be this precise or more generous. Search_v2 is designed to take the inputs from the typeahead suggestion, which will have the exact values. However, if it's designed to also accept inputs from the everyday user, it may be more prudent to adjust things. Let me know your thoughts!

**Comment by josh-chamberlain** [comment]
@maxachis the precision required is OK for now, since these just come from the typeahead endpoint.

I can't test this to my full satisfaction, but that's mostly because of API key nonsense. If you address the state_iso query from above, I think we could merge this

**Comment by maxachis** [comment]
@josh-chamberlain This has been successfully merged! Have a looksee at https://data-sources-v2.pdap.dev/api. The API instructions should provide enough information, and if you're still having API Key issues we can give that a look as well.

**Pull request merged**
