### PR TITLE
Setup GitHub actions tests

### PR DESCRIPTION
**Pull request by maxachis**
#### Fixes

* None. QoL improvement.

#### Description

* Sets up Github Action tests and removes unused tests
* Modify certain so that they properly bypass the `api_required` decorator 

#### Testing

* Well, see how this Github Action runs on this pull request! If the tests pass, we're good! 

#### Performance

* TBD

#### Docs

* Not applicable.

### CODE REVIEW

**Comment by maxachis** [comment]
@josh-chamberlain In order to get these tests working against the test database, I removed the IP whitelisting for the Dev Database -- now anyone can access the Dev database from any IP address. There's unfortunately not an easy way around it that still uses Github Actions -- the IP address of a Github Action is not static, so there'd be no easy way to whitelist it.

**Comment by josh-chamberlain** [comment]
@maxachis we'd need to eventually replicate this in production, right?

**Comment by maxachis** [comment]
@josh-chamberlain Depends on what you mean. If you mean whether we should have these tests against the development database also be added to the production repositories, absolutely! 

If you men whether we should have the tests occur on the production database, _noOOoooOoo_. Risks interfering with production application and is redundant because the dev database is meant to mirror the production database. But I'm pretty sure you meant the former.

**Comment by josh-chamberlain** [comment]
@maxachis ok, that makes sense. thank you

**Pull request merged**
