### PR TITLE
feature: main search route

### PR DESCRIPTION
**Pull request by joshuagraber**
Adds the initial search functionality to the main page of the data sources v2 app.

See https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/249

## Still to do
- [ ] Add unit tests for new components and utils 

## To test
1. Run the API locally
2. Run the client app locally
3. Perform a search
4. Check the console for the path to which we will eventually redirect for our search. Not that all search values are present in URL query params

It should look something like this:

https://github.com/user-attachments/assets/bec7314f-bf67-4246-b1e4-eaf6a277abef

### CODE REVIEW

**Review by maxachis — CHANGES_REQUESTED** [review]
I _**LOVE IT**_ 🔥. It's so beautiful 🥲.

We do definitely need one adjustment. The original requirements state that it should trigger after 2 characters, but currently, it seems to be triggering on 1:

```
127.0.0.1 - - [07/Aug/2024 16:19:08] "GET /search/typeahead-suggestions?query=P HTTP/1.1" 200 -
127.0.0.1 - - [07/Aug/2024 16:19:09] "GET /search/typeahead-suggestions?query=Pi HTTP/1.1" 200 -
127.0.0.1 - - [07/Aug/2024 16:19:10] "GET /search/typeahead-suggestions?query=Pitt HTTP/1.1" 200 -
127.0.0.1 - - [07/Aug/2024 16:19:11] "GET /search/typeahead-suggestions?query=Pitts HTTP/1.1" 200 -
127.0.0.1 - - [07/Aug/2024 16:19:12] "GET /search/typeahead-suggestions?query=Pittsb HTTP/1.1" 200 -
127.0.0.1 - - [07/Aug/2024 16:19:13] "GET /search/typeahead-suggestions?query=Pittsbu HTTP/1.1" 200 -
127.0.0.1 - - [07/Aug/2024 16:19:13] "GET /search/typeahead-suggestions?query=Pittsbur HTTP/1.1" 200 -
127.0.0.1 - - [07/Aug/2024 16:19:14] "GET /search/typeahead-suggestions?query=Pittsburg HTTP/1.1" 200 -
127.0.0.1 - - [07/Aug/2024 16:19:16] "GET /search/typeahead-suggestions?query=C HTTP/1.1" 200 -
127.0.0.1 - - [07/Aug/2024 16:19:17] "GET /search/typeahead-suggestions?query=Cl HTTP/1.1" 200 -
127.0.0.1 - - [07/Aug/2024 16:19:17] "GET /search/typeahead-suggestions?query=Cle HTTP/1.1" 200 -
127.0.0.1 - - [07/Aug/2024 16:19:17] "GET /search/typeahead-suggestions?query=Clea HTTP/1.1" 200 -
127.0.0.1 - - [07/Aug/2024 16:19:17] "GET /search/typeahead-suggestions?query=Cleavel HTTP/1.1" 200 -
127.0.0.1 - - [07/Aug/2024 16:19:18] "GET /search/typeahead-suggestions?query=Cleavela HTTP/1.1" 200 -
127.0.0.1 - - [07/Aug/2024 16:19:18] "GET /search/typeahead-suggestions?query=Cleaveland HTTP/1.1" 200 -
127.0.0.1 - - [07/Aug/2024 16:19:20] "GET /search/typeahead-suggestions?query=C HTTP/1.1" 200 -
127.0.0.1 - - [07/Aug/2024 16:19:21] "GET /search/typeahead-suggestions?query=Cleveland HTTP/1.1" 200 -
```

And of course, we need clarification on whether we're doing only one record type at a time, or multiple.

**Comment by josh-chamberlain** [comment]
@maxachis oop, I didn't see that you were already aware—yes, record type category is a multi-select.

https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/386

we can just delete this issue if you want to make changes on the branch.

**Comment by josh-chamberlain** [comment]
this looks great by the way @joshuagraber. I think little tweaks to type and spacing will happen, but this is a great foundation for those and it's too early at the moment.

**Comment by josh-chamberlain** [comment]
@joshuagraber 

1. #72 has merged to `dev`, so we should allow multi-selects for record type now.
2. I removed the requirement for allowing a fallback string search when people type a location name we don't recognize; I adjusted the wireframe too, but in the case where our typeahead endpoint returns no results, we should display "**No results found.** Please check your spelling and search for a place in the United States."

**Review by maxachis — APPROVED** [review]
Typeahead suggestion now starts at 2 characters as expected, and also I continue to love it. Approved!

**Comment by joshuagraber** [comment]
Nice, thank you @maxachis. 

@josh-chamberlain Thank you for that update. I changed the not-found UI to be a non-interactive element that displays the message you suggested. We should be g2g for this PR. We'll get to the search results in the next one.

**Review by josh-chamberlain — APPROVED** [review]

**Pull request merged**
