### PR TITLE
refactor: search results redesign

### PR DESCRIPTION
**Pull request by joshuagraber**
## To test
1. Pull branch, run backend, run client
2. Search for any location with some data sources
3. Check out page.

Known issues:
- the mobile design <= 500px or so

### CODE REVIEW

**Review by josh-chamberlain — CHANGES_REQUESTED** [review]
Very nice! I think there is some room for polish on spacing and sizing—but in my opinion that can follow.

Some structural things I think should happen in a following PR: https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/449

**Comment by vikramrojo** [comment]
@josh-chamberlain is it possible to push this PR to the dev environment?

**Comment by josh-chamberlain** [comment]
@vikramrojo asked if we could merge this to dev for testing, so that's done! I did link to an issue above with some structural enhancements.

**Comment by vikramrojo** [comment]
Thanks @josh-chamberlain, I can work with the deployed app and add my feedback to that issue as well.

**Pull request merged**
