### PR TITLE
DatabaseClient connection overhaul

### PR DESCRIPTION
**Pull request by EvilDrPurple**
#### Fixes

* Part of reconciliation of https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/303 and https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/318

#### Description

* In `DatabaseClient`, when a method is called, `cursor_manager` is now used to create a cursor. The cursor is closed and discarded once the method concludes its execution. Before, a cursor object would be created and passed to the `DatabaseClient` object on initialization and used for as long as the object was used.
* A new connection object is opened with each `DatabaseClient` instance and then closed after use of the instance concludes. 
* These changes come at a significant cost to execution time while testing, and may be rethought later.

#### Testing

* Checkout the branch
* Setup testing environment like normal
* Run `pytest` in the terminal

#### Performance

* Running `pytest test_database_client.py` increases execution by almost double, `23.63` seconds vs `43.17` seconds
* Running `pytest` increases execution time from `94` seconds to `164` seconds

### CODE REVIEW

**Comment by maxachis** [comment]
I'm quite happy with these changes! Excellent work as usual, Kylie.

I did make three changes, and elected to do them myself just to keep things moving quickly and to enable me to utilize this updated database client in some of the new code.

## Create Singleton Connection Object

To avoid the overhead of continually creating and closing connections, I updated `initialize_psycopg2_connection()` to call a Singleton Connection object which always returns the same connection whenever it's called, and which creates a new connection if an existing connection does not exist or is closed. 

Consequently, I removed all references to closing the connection object. Now, the connection logic more mirrors how the database client originally was (but with less of the other annoying overhead of passing the connection object.

## Modify `execute_raw_sql()` to always return a list if it has results

The previous design of `execute_raw_sql()` returned a single result if the results were one, and a list of results if the results were more than one. To test that only one result was in place, type checking was done to ensure the result was a DictRow rather than a list. 

This made things slightly more iffy in terms of testing, because it required someone to know that, if only one result was returned, the type would be different. That might pose problems if the type of result returned ever changed. 

To simplify things, I elected to have it always return a list of its results, even if there's only one result. I modified tests accordingly so that now, instead of checking the type of the result, they instead check that only one result is returned. 

## Remove rollback logic

The simplification of connection logic was causing conflicts with tests that involved inserting test data and rolling back afterwards. I eliminated the rollback logic to make tests pass properly. There is now some dead code that needs refactoring, but for now that's a minor issue.

**Comment by josh-chamberlain** [comment]
@EvilDrPurple @maxachis nice work! 

-does this merit changes in `CONTRIBUTING` or `README` about using the `DatabaseClient`? Something to consider for further SQLAlchemy work, since this is pretty foundational.
- does the test data still need to be rolled back? At one point we were using the production database, but that's no longer the case for these tests, right?

**Comment by EvilDrPurple** [comment]
>     * does the test data still need to be rolled back? At one point we were using the production database, but that's no longer the case for these tests, right?

@josh-chamberlain I can at least provide an answer to this. If we use static values in the tests that are inserted into the database, then it would pose a problem for anything with a Unique Constraint on subsequent test runs. However, I think we've changed all the values to be randomized so it may not be an issue anymore!

**Comment by maxachis** [comment]
Heck yeah, tag teaming with @EvilDrPurple 🙏

> * does this merit changes in `CONTRIBUTING` or `README` about using the `DatabaseClient`? Something to consider for further SQLAlchemy work, since this is pretty foundational.

@josh-chamberlain 

Depends on how granular we want to get in the Markdown files. My thinking is that the documentation in the modules themselves should provide the information necessary. While the Markdown files don't exclusively focus on information that can't be easily determined from the app alone, they do generally focus on such topics -- discussing the relation of the project to databases, our general goals, and providing information on where to start in the app.

Additionally, DatabaseClient implementation was not previously mentioned within the markdown files. I will ultimately defer to your judgment on the matter.

Either way, it may be worth making an issue to go through the documentation and add comments and docstrings where needed (might be a good first issue, since a fresh pair of eyes would be most primed to be confused by a lack of documentation).

**Comment by josh-chamberlain** [comment]
Nice, I think rolling back after tests is less of an issue, then. Plus, we have means and ways of resetting the test db.

We can hold off on the DatabaseClient documentation, as the name does give people a clue as to where to start. I like the idea of the markdown files commenting on the overall structure, but we can hold off all the same.

**Pull request merged**
