### PR TITLE
Mc add endpoint tests

### PR DESCRIPTION
**Pull request by maxachis**
#### Fixes

* None. Quality of life update.

#### Description

Refactor create_app Function in app.py

- Moved initialization of the psycopg2 connection out of the create_app function and into its parameter list.
- Enhanced flexibility and reusability of the function, allowing it to accept different database connections.
- Simplified testing and opened the possibility for using different database management systems in the future.
- Remove Unused Methods from PsycopgResource Class

Cleaned up the PsycopgResource class by removing methods that were not being used.

Add Thorough Tests for All Application Endpoints

- Created a new file, test_endpoints.py, dedicated to comprehensive testing of all application endpoints.
- Utilized Pytest to ensure each endpoint correctly calls (or doesn’t call) the appropriate methods in their supporting classes.
- Included tests for both allowed and not allowed methods for each endpoint.

#### Testing

* Run `test_endpoints.py`

#### Performance

* Minimal additional test overhead. 

#### Docs

* Not applicable

### CODE REVIEW

**Comment by josh-chamberlain** [comment]
@maxachis nice. outside of API endpoints, what are the ways that the database can change, currently?

**Comment by maxachis** [comment]
@josh-chamberlain If you're talking about how the schema can change, at the moment we're looking mostly at the removal of a view columns or the normalization of tables. However, all of this would be on pause until I finish setting up a suite of integration tests which will give us confidence that any changes I make aren't breaking things substantially.

I think that answers your question, but if you meant something else, let me know!

**Comment by josh-chamberlain** [comment]
@maxachis I meant data in the database—are we programmatically making changes to the data _without_ using the API anywhere?

**Comment by maxachis** [comment]
> @maxachis I meant data in the database—are we programmatically making changes to the data _without_ using the API anywhere?

A few places. Things such as the Google Agency searcher, as designed, would be inserting data directly into the database. And then there are some things, such as user roles, which don't appear to be governed by an API endpoint and so must be modified through direct SQL queries. As a heuristic (for my own sake rather than yours), any SQL string located in a file that isn't in the data-sources-app repository (and isn't a test) would strongly suggest someplace that's modifying the database outside of an endpoint.

**Comment by josh-chamberlain** [comment]
@maxachis thanks. plus, probably only a few python files should contain endpoints...I made a new issue: https://github.com/Police-Data-Accessibility-Project/data-sources-app/issues/315

**Pull request merged**
